include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    await_only_futures: ignore
    file_names: ignore
    non_constant_identifier_names: ignore
    use_build_context_synchronously: ignore
